### ISSUE TITLE
classpath 'com.android.tools.build:gradle:3.6.3' 报错 

### ISSUE THREAD

**Issue by ebtarszpn** [zhujiang521/AndroidAOP#1]
报错内容：
Cannot cast object ‘com.android.build.gradle.internal.pipeline.TransformTask$2$1@74dbb0ae’ with class ‘com.android.build.gradle.internal.pipeline.TransformTask$2$1’ to class ‘com.android.build.gradle.internal.pipeline.TransformTask

解决方案：改成3.4.0就可以了

Android studio版本：3.6.3

module依赖如下：
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.zhujiang521:AndroidAOP:1.0.1'
}

**Comment by zhujiang521** [comment]
问题原因是之前引入aspectjx的版本有点低，不支持3.6.0以上，在1.1.1中已修复，可直接更新进行使用。
